### ISSUE TITLE
Exit preview?

### ISSUE THREAD

**Issue by marcobarbosa** [sanity-io/sanity-plugin-iframe-pane#61]
Not sure if this is out of scope but asking anyway:

Is it possible to have an "exit preview" button that would link to a `/api/exit-preview` of some sort?

Right now, once somebody views the preview, it will be in preview mode forever. Probably not related to this plugin but since I have no control over it, it would be nice to rely on this plugin to also exit preview.

Thoughts?

**Comment by john-rock** [comment]
Hmm, I don't think that it's necessarily out of scope for this project. A button could be added and have an option to set the exit preview route in the code. 

Right now I'm handling the exit preview by adding a custom banner on the page with a button that links to a `/api/exit-preview` route but it would be nice to have this built into the plugin.

Curious to hear what others think.

**Comment by stipsan** [comment]
This is a bit tricky to do, because we can't reliably know if the iframe is in draft/preview mode or not from the iframe pane side.
It's equally confusing to see an "Exit Preview" button that can always be clicked because it fails to detect that it's exited so we need a proper solution for this to add it in the plugin.

The way we're currently handling this in our own templates is by showing a bar at the top.
![image](https://github.com/sanity-io/sanity-plugin-iframe-pane/assets/81981/701cf015-32be-415a-a254-aa2e83f201a4)

https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website/blob/main/components/preview/PreviewBanner.tsx

**Comment by gpoole** [comment]
Assuming you're using Next.js for this @marcobarbosa?

I agree with the banner as @stipsan mentions. You can detect if you're in an iframe from the frontend side with `window.self !== window.top` and hide the banner so it doesn't get in the way when you view the site in the iframe within Sanity, but still have the banner show if your users directly navigate to the site with the preview cookie set. This also handles the case where your user has clicked the "open" button to open the preview in a new tab, or that they've been sent the preview link by someone else, so I think it's the best option.

**Comment by marcobarbosa** [comment]
@gpoole Cool suggestion. Yes, I'm on Next. Thanks for the input too, @stipsan.
